/**:
  ros__parameters:
    poses:
      - shutdown_pose
      - initial_pose
      - initial_moving_pose
      - detecting_pose
      - following_pose
      - grasp_raise_hand_pose
      - pass_pose
      - pre_table_grasp_pose
      - pre_table_put_pose
      - pre_shelf_put_pose
      - grasp_detecting_pose

    shutdown_pose:
      arm_shoulder_roll  : 0.0
      arm_shoulder_pitch : -2.45
      arm_elbow_pitch    : 0.44
      arm_forearm_roll   : 0.0
      arm_wrist_pitch    : 2.15
      arm_wrist_roll     : 0.0
      hand               : 0.0
      head_yaw           : 0.0
      head_pitch         : 1.68

    initial_pose:
      arm_shoulder_roll  : 0.0
      arm_shoulder_pitch : -1.5708
      arm_elbow_pitch    : 0.0
      arm_forearm_roll   : 0.0
      arm_wrist_pitch    : 0.0
      arm_wrist_roll     : 0.0
      hand               : 0.0
      head_yaw           : 0.0
      head_pitch         : 0.0

    initial_moving_pose:
      arm_shoulder_roll  : 0.0
      arm_shoulder_pitch : -2.2
      arm_elbow_pitch    : -1.5708
      arm_forearm_roll   : 0.0
      arm_wrist_pitch    : 2.15
      arm_wrist_roll     : 0.0
      hand               : 0.0
      head_yaw           : 0.0
      head_pitch         : 0.0

    detecting_pose:
      arm_shoulder_roll  : 0.0
      arm_shoulder_pitch : -2.2
      arm_elbow_pitch    : -1.04
      arm_forearm_roll   : 1.5708
      arm_wrist_pitch    : 1.5708
      arm_wrist_roll     : 0.0
      hand               : 0.0
      head_yaw           : 0.0
      head_pitch         : 0.6108

    following_pose:
      arm_shoulder_roll  : 0.0
      arm_shoulder_pitch : -1.5708
      arm_elbow_pitch    : 0.0
      arm_forearm_roll   : 0.0
      arm_wrist_pitch    : 0.0
      arm_wrist_roll     : 0.0
      hand               : 0.0
      head_yaw           : 0.0
      head_pitch         : 0.0
    
    grasp_raise_hand_pose:
      arm_shoulder_roll  : 0.0
      arm_shoulder_pitch : -2.2
      arm_elbow_pitch    : -1.04
      arm_forearm_roll   : 0.0
      arm_wrist_pitch    : 0.0
      arm_wrist_roll     : 0.0
      hand               : 2.5
      head_yaw           : 0.0
      head_pitch         : 0.523
      
    pass_pose:
      arm_shoulder_roll  : 0.0
      arm_shoulder_pitch : -0.2
      arm_elbow_pitch    : -1.5708
      arm_forearm_roll   : 0.0
      arm_wrist_pitch    : 0.0
      arm_wrist_roll     : 0.0
      hand               : 2.5
      head_yaw           : 0.0
      head_pitch         : 0.0

    pre_table_grasp_pose:
      arm_shoulder_roll  : 0.0
      arm_shoulder_pitch : -2.2
      arm_elbow_pitch    : -1.5708
      arm_forearm_roll   : 0.0
      arm_wrist_pitch    : 2.15
      arm_wrist_roll     : 0.0
      hand               : 0.0
      head_yaw           : 0.0
      head_pitch         : 0.523

    pre_table_put_pose:
      arm_shoulder_roll  : 0.0
      arm_shoulder_pitch : -2.2
      arm_elbow_pitch    : -1.04
      arm_forearm_roll   : 0.0
      arm_wrist_pitch    : 0.0
      arm_wrist_roll     : 0.0
      hand               : 2.5
      head_yaw           : 0.0
      head_pitch         : 0.523

    pre_shelf_put_pose:
      arm_shoulder_roll  : 0.0
      arm_shoulder_pitch : -1.047
      arm_elbow_pitch    : 0.423
      arm_forearm_roll   : 0.0
      arm_wrist_pitch    : -1.047
      arm_wrist_roll     : -1.5708
      hand               : 2.5
      head_yaw           : 0.0
      head_pitch         : 0.0

    grasp_detecting_pose:
      arm_shoulder_roll  : 0.0
      arm_shoulder_pitch : -2.2
      arm_elbow_pitch    : -1.04
      arm_forearm_roll   : 1.5708
      arm_wrist_pitch    : 1.5708
      arm_wrist_roll     : 0.0
      hand               : 2.5
      head_yaw           : 0.0
      head_pitch         : 0.523


