/**:
  ros__parameters:
    poses:
      - initial_pose
      - detecting_pose
      - following_pose

    pose_check_door:
      arm_shoulder_roll  : 0.0
      arm_shoulder_pitch : -1.8
      arm_elbow_pitch    : 1.5
      arm_forearm_roll   : 0.0
      arm_wrist_pitch    : 0.5
      arm_wrist_roll     : 0.0
      hand               : 0.0
      head_yaw           : 0.0
      head_pitch         : 0.7

    pose_check_sign:
      arm_shoulder_roll  : 0.0
      arm_shoulder_pitch : -1.8
      arm_elbow_pitch    : 1.5
      arm_forearm_roll   : 0.0
      arm_wrist_pitch    : 0.5
      arm_wrist_roll     : 0.0
      hand               : 0.0
      head_yaw           : 0.0
      head_pitch         : 0.3

    pose_detect_customer:
      arm_shoulder_roll  : 0.0
      arm_shoulder_pitch : -1.8
      arm_elbow_pitch    : 1.5
      arm_forearm_roll   : 0.0
      arm_wrist_pitch    : 0.5
      arm_wrist_roll     : 0.0
      hand               : 0.0
      head_yaw           : 0.0
      head_pitch         : -0.1

    pose_find_object:
      arm_shoulder_roll  : 0.0
      arm_shoulder_pitch : -1.8
      arm_elbow_pitch    : 1.5
      arm_forearm_roll   : 0.0
      arm_wrist_pitch    : 0.5
      arm_wrist_roll     : 0.0
      hand               : 0.0
      head_yaw           : 0.0
      head_pitch         : 0.2