/sobit_light_joint_controller:
  ros__parameters:
    poses:
      names:          ['initial_pose', 'detecting_pose', 'raise_hand']
      initial_pose:   [0.0, -1.5708, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      detecting_pose: [0.0, -1.5708, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.7854]
      raise_hand:     [0.0, -1.5708, -1.5708, 0.0, 0.0, 0.0, 0.7854, 0.0, 0.0]