controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

velocity_controller:
  ros__parameters:
    joints:
      - arm_shoulder_roll_joint
      - arm_shoulder_pitch_joint
      - arm_shoulder_pitch_sub_joint
      - arm_elbow_pitch_joint
      - arm_forearm_roll_joint
      - arm_wrist_pitch_joint
      - arm_wrist_roll_joint
      - hand_joint
      - head_yaw_joint
      - head_pitch_joint

joint_trajectory_controller:
  ros__parameters:
    joints:
      - arm_shoulder_roll_joint
      - arm_shoulder_pitch_joint
      - arm_shoulder_pitch_sub_joint
      - arm_elbow_pitch_joint
      - arm_forearm_roll_joint
      - arm_wrist_pitch_joint
      - arm_wrist_roll_joint
      - hand_joint
      - head_yaw_joint
      - head_pitch_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity
