controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

velocity_controller:
  ros__parameters:
    joints:
      - arm_1_joint
      - arm_2_joint
      - arm_2_sub_joint
      - arm_3_joint
      - arm_4_joint
      - arm_5_joint
      - arm_6_joint
      - hand_finger_l_joint
      - head_pan_joint
      - head_tilt_joint

joint_trajectory_controller:
  ros__parameters:
    joints:
      - arm_1_joint
      - arm_2_joint
      - arm_2_sub_joint
      - arm_3_joint
      - arm_4_joint
      - arm_5_joint
      - arm_6_joint
      - hand_finger_l_joint
      - head_pan_joint
      - head_tilt_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity
