controller_manager:
  ros__parameters:
    update_rate: &loop_hz 10  # Hz
    use_sim_time: true

    arm_controller:
      type: "joint_trajectory_controller/JointTrajectoryController"
    gripper_controller:
      type: "position_controllers/GripperActionController"
    diff_controller:
      type: "diff_drive_controller/DiffDriveController"

    joint_state_controller:
      type: "joint_state_broadcaster/JointStateBroadcaster"


# https://control.ros.org/humble/doc/ros2_controllers/joint_trajectory_controller/doc/userdoc.html
arm_controller:
  ros__parameters:
    joints:
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
      - arm_4_joint
      - arm_5_joint
      - arm_6_joint

    command_interfaces:
      - position

    state_interfaces:
      - position

    state_publish_rate: *loop_hz
    action_monitor_rate: *loop_hz

    allow_partial_joints_goal: false
    open_loop_control: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      joint1:
        trajectory: 0.05
        goal: 0.03


# https://control.ros.org/humble/doc/ros2_controllers/gripper_controllers/doc/userdoc.html
gripper_controller:
  ros__parameters:
    action_monitor_rate: *loop_hz
    allow_stalling: false
    goal_tolerance: 0.01
    joint: hand_l_finger_joint
    max_effort: 10.0
    stall_timeout: 1.0
    stall_velocity_threshold: 0.001


# https://control.ros.org/humble/doc/ros2_controllers/diff_drive_controller/doc/userdoc.html
diff_controller:
  ros__parameters:
    left_wheel_names: ["base_l_drive_wheel_joint"]
    right_wheel_names: ["base_r_drive_wheel_joint"]

    wheel_separation: 0.200
    #wheels_per_side: 1  # actually 2, but both are controlled by 1 signal
    wheel_radius: 0.09

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: *loop_hz
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    open_loop: true
    enable_odom_tf: true

    cmd_vel_timeout: 0.5
    #publish_limited_velocity: true
    use_stamped_vel: false
    #velocity_rolling_window_size: 10

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    linear.x.max_acceleration: 1.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0
    angular.z.max_acceleration: 1.0
    angular.z.min_acceleration: -1.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0